// 一回限りのリバースマイグレーション。
//
// lib/src/castle.dart の knownCastles をリフレクションせず直接 import で
// 走査し、data/castles.txt に ASCII フォーマットで書き出す。
//
// 使い方:
//   cd <repo>
//   dart run tool/export_castles_to_ascii.dart
//
// 出力フォーマットは forward codegen (tool/generate_castles.dart) が解釈で
// きる形にする。`reverse → forward → diff` がゼロになる必要がある。

import 'dart:io';

import 'package:tsshogi/src/castle.dart';
import 'package:tsshogi/src/color.dart';
import 'package:tsshogi/src/piece.dart';

import 'template_parser.dart';

void main() {
  final StringBuffer buf = StringBuffer();
  buf.writeln('# GENERATED by tool/export_castles_to_ascii.dart');
  buf.writeln('# Source: lib/src/castle.dart knownCastles');
  buf.writeln('# Hand-editable from here on. Regenerate Dart with:');
  buf.writeln('#   dart run tool/generate_castles.dart');
  buf.writeln();
  for (final CastleTemplate t in knownCastles) {
    buf.writeln('=== name: ${t.name}');
    if (t.parent != null) buf.writeln('parent: ${t.parent}');
    if (t.aliases.isNotEmpty) buf.writeln('aliases: ${t.aliases.join(', ')}');
    final String? plyLine = formatPlyHeader(plyEq: t.plyEq, plyMax: t.plyMax);
    if (plyLine != null) buf.writeln(plyLine);
    final List<PlacementCell> cells = _toCells(t.placements);
    final String? boardLine = formatBoardHeader(cells);
    if (boardLine != null) buf.writeln(boardLine);
    final String? handLine = formatHandHeader(cells);
    if (handLine != null) buf.writeln(handLine);
    final String? igyokuLine = formatIgyokuHeader(cells);
    if (igyokuLine != null) buf.writeln(igyokuLine);
    for (final String line in formatUnmovedHeaders(cells)) {
      buf.writeln(line);
    }
    for (final String line in formatVisitedHeaders(cells)) {
      buf.writeln(line);
    }
    buf.writeln();
    final List<List<String>> grid = buildGrid(cells);
    for (final List<String> row in grid) {
      buf.writeln(row.join(' '));
    }
    buf.writeln();
  }
  File('data/castles.txt').writeAsStringSync(buf.toString());
  stdout.writeln('Wrote ${knownCastles.length} castles to data/castles.txt');
}

List<PlacementCell> _toCells(List<CastleRequirement> placements) {
  final List<PlacementCell> out = <PlacementCell>[];
  for (final CastleRequirement req in placements) {
    switch (req) {
      case PiecePlacement():
        out.add(
          PlacementCell(
            file: req.file,
            rank: req.rank,
            kind: req.color == Color.black ? 'exact' : 'opponent',
            pieceTypes: <String>[req.pieceType.name],
          ),
        );
      case AnyOfPieces():
        out.add(
          PlacementCell(
            file: req.file,
            rank: req.rank,
            kind: 'anyOf',
            pieceTypes: req.options.map((PieceType p) => p.name).toList(),
          ),
        );
      case EmptySquare():
        out.add(PlacementCell(
          file: req.file,
          rank: req.rank,
          kind: 'empty',
        ));
      case NotOfPieces():
        out.add(PlacementCell(
          file: req.file,
          rank: req.rank,
          kind: 'notOf',
          pieceTypes: req.excluded.map((PieceType p) => p.name).toList(),
        ));
      case AnyPiece():
        out.add(PlacementCell(
          file: req.file,
          rank: req.rank,
          kind: 'anyPiece',
        ));
      case PieceAnywhere():
        out.add(PlacementCell(
          kind: 'pieceAnywhere',
          pieceTypes: <String>[req.pieceType.name],
        ));
      case HandPiece():
        out.add(PlacementCell(
          kind: 'handPiece',
          pieceTypes: <String>[req.pieceType.name],
          minCount: req.minCount,
        ));
      case PieceUnmoved():
        out.add(PlacementCell(
          kind: 'pieceUnmoved',
          file: req.file,
          rank: req.rank,
        ));
      case PieceVisited():
        out.add(PlacementCell(
          kind: 'pieceVisited',
          file: req.file,
          rank: req.rank,
          pieceTypes: <String>[req.pieceType.name],
        ));
      case KingIgyoku():
        out.add(PlacementCell(kind: 'kingIgyoku'));
    }
  }
  return out;
}
