// 一回限りのリバースマイグレーション (戦法版)。
//
// lib/src/strategy.dart の knownStrategies を data/strategies.txt に
// ASCII フォーマットで書き出す。`reverse → forward → diff` がゼロになる
// 必要がある。

import 'dart:io';

import 'package:tsshogi/src/castle.dart';
import 'package:tsshogi/src/piece.dart';
import 'package:tsshogi/src/strategy.dart';

import 'template_parser.dart';

void main() {
  final StringBuffer buf = StringBuffer();
  buf.writeln('# GENERATED by tool/export_strategies_to_ascii.dart');
  buf.writeln('# Source: lib/src/strategy.dart knownStrategies');
  buf.writeln('# Hand-editable from here on. Regenerate Dart with:');
  buf.writeln('#   dart run tool/generate_strategies.dart');
  buf.writeln();
  for (final StrategyTemplate t in knownStrategies) {
    buf.writeln('=== name: ${t.name}');
    if (t.parent != null) buf.writeln('parent: ${t.parent}');
    if (t.aliases.isNotEmpty) buf.writeln('aliases: ${t.aliases.join(', ')}');
    if (t.side != StrategySide.either) {
      buf.writeln('side: ${t.side.name}');
    }
    buf.writeln();
    final List<PlacementCell> cells = _toCells(t.placements);
    final List<List<String>> grid = buildGrid(cells);
    for (final List<String> row in grid) {
      buf.writeln(row.join(' '));
    }
    buf.writeln();
  }
  File('data/strategies.txt').writeAsStringSync(buf.toString());
  stdout.writeln(
    'Wrote ${knownStrategies.length} strategies to data/strategies.txt',
  );
}

List<PlacementCell> _toCells(List<CastleRequirement> placements) {
  final List<PlacementCell> out = <PlacementCell>[];
  for (final CastleRequirement req in placements) {
    if (req is PiecePlacement) {
      out.add(
        PlacementCell(
          file: req.file,
          rank: req.rank,
          kind: 'exact',
          pieceTypes: <String>[req.pieceType.name],
        ),
      );
    } else if (req is AnyOfPieces) {
      out.add(
        PlacementCell(
          file: req.file,
          rank: req.rank,
          kind: 'anyOf',
          pieceTypes: req.options.map((PieceType p) => p.name).toList(),
        ),
      );
    } else {
      throw StateError('unknown CastleRequirement subtype: $req');
    }
  }
  return out;
}
