// Forward codegen: data/strategies.txt → lib/src/generated/strategies.g.dart
//
// 使い方:
//   cd <repo>
//   dart run tool/generate_strategies.dart

import 'dart:io';

import 'template_parser.dart';

void main() {
  final String input = File('data/strategies.txt').readAsStringSync();
  final List<ParsedTemplate> templates = parseTemplateFile(input);
  final String output = generateStrategyDart(templates);
  File('lib/src/generated/strategies.g.dart').writeAsStringSync(output);
  stdout.writeln(
    'Wrote ${templates.length} strategies to '
    'lib/src/generated/strategies.g.dart',
  );
}

/// テンプレ列 → strategies.g.dart 文字列。
String generateStrategyDart(List<ParsedTemplate> templates) {
  final StringBuffer buf = StringBuffer();
  buf.writeln('// GENERATED by tool/generate_strategies.dart. DO NOT EDIT.');
  buf.writeln('// Source: data/strategies.txt');
  buf.writeln('//');
  buf.writeln('// To regenerate: dart run tool/generate_strategies.dart');
  buf.writeln();
  buf.writeln("import '../castle.dart';");
  buf.writeln("import '../color.dart';");
  buf.writeln("import '../piece.dart';");
  buf.writeln("import '../strategy.dart';");
  buf.writeln();
  buf.writeln('const List<StrategyTemplate> strategies = <StrategyTemplate>[');
  for (final ParsedTemplate t in templates) {
    buf.writeln('  StrategyTemplate(');
    buf.writeln('    name: ${_dartString(t.name)},');
    if (t.parent != null) {
      buf.writeln('    parent: ${_dartString(t.parent!)},');
    }
    if (t.aliases.isNotEmpty) {
      buf.writeln(
        '    aliases: <String>[${t.aliases.map(_dartString).join(', ')}],',
      );
    }
    if (t.side != null && t.side != 'either') {
      buf.writeln('    side: StrategySide.${t.side},');
    }
    if (t.plyEq != null) {
      buf.writeln('    plyEq: ${t.plyEq},');
    }
    if (t.plyMax != null) {
      buf.writeln('    plyMax: ${t.plyMax},');
    }
    if (t.evaluateAtGameEnd) {
      buf.writeln('    evaluateAtGameEnd: true,');
    }
    if (t.outbreakSkip) {
      buf.writeln('    outbreakSkip: true,');
    }
    if (t.killCountLteq != null) {
      buf.writeln('    killCountLteq: ${t.killCountLteq},');
    }
    if (t.killOnly) {
      buf.writeln('    killOnly: true,');
    }
    if (t.orderKey != null) {
      buf.writeln("    orderKey: '${t.orderKey}',");
    }
    if (t.handEq != null) {
      buf.writeln('    handEq: ${_handMapLiteral(t.handEq!)},');
    }
    if (t.opHandEq != null) {
      buf.writeln('    opHandEq: ${_handMapLiteral(t.opHandEq!)},');
    }
    if (t.handNotIn.isNotEmpty) {
      final String items =
          t.handNotIn.map((String n) => 'PieceType.$n').join(', ');
      buf.writeln('    handNotIn: <PieceType>[$items],');
    }
    if (t.noPawnInHand) {
      buf.writeln('    noPawnInHand: true,');
    }
    if (t.onlyPawnsInHand) {
      buf.writeln('    onlyPawnsInHand: true,');
    }
    if (t.placements.isEmpty) {
      buf.writeln('    placements: <CastleRequirement>[],');
    } else {
      buf.writeln('    placements: <CastleRequirement>[');
      for (final PlacementCell p in t.placements) {
        buf.writeln('      ${_formatPlacement(p)},');
      }
      buf.writeln('    ],');
    }
    buf.writeln('  ),');
  }
  buf.writeln('];');
  return buf.toString();
}

String _handMapLiteral(Map<String, int> m) {
  final String entries =
      m.entries.map((MapEntry<String, int> e) => 'PieceType.${e.key}: ${e.value}').join(', ');
  return '<PieceType, int>{$entries}';
}

String _formatPlacement(PlacementCell p) {
  switch (p.kind) {
    case 'exact':
      final String enumName = p.pieceTypes.single;
      return 'PiecePlacement(${p.file}, ${p.rank}, PieceType.$enumName)';
    case 'opponent':
      final String enumName = p.pieceTypes.single;
      return 'PiecePlacement(${p.file}, ${p.rank}, '
          'PieceType.$enumName, color: Color.white)';
    case 'anyOf':
      final String opts =
          p.pieceTypes.map((String n) => 'PieceType.$n').join(', ');
      return 'AnyOfPieces(${p.file}, ${p.rank}, <PieceType>[$opts])';
    case 'empty':
      return 'EmptySquare(${p.file}, ${p.rank})';
    case 'anyPiece':
      if (p.anySide) {
        return 'AnyPiece(${p.file}, ${p.rank}, anySide: true)';
      }
      return 'AnyPiece(${p.file}, ${p.rank})';
    case 'anyPlacement':
      final String coords = p.squares
          .map((({int file, int rank}) s) => '(file: ${s.file}, rank: ${s.rank})')
          .join(', ');
      final String color = p.opponent ? ', color: Color.white' : '';
      return 'AnyPlacement(PieceType.${p.pieceTypes.single}, '
          '<({int file, int rank})>[$coords]$color)';
    case 'notOf':
      final String opts =
          p.pieceTypes.map((String n) => 'PieceType.$n').join(', ');
      final String color = p.opponent ? ', color: Color.white' : '';
      return 'NotOfPieces(${p.file}, ${p.rank}, <PieceType>[$opts]$color)';
    case 'pieceAnywhere':
      return 'PieceAnywhere(PieceType.${p.pieceTypes.single})';
    case 'handPiece':
      final String name = p.pieceTypes.single;
      if (p.opponent) {
        return 'HandPiece(PieceType.$name, ${p.minCount}, Color.white)';
      }
      if (p.minCount == 1) {
        return 'HandPiece(PieceType.$name)';
      }
      return 'HandPiece(PieceType.$name, ${p.minCount})';
    case 'pieceUnmoved':
      return 'PieceUnmoved(${p.file}, ${p.rank})';
    case 'pieceVisited':
      final String name = p.pieceTypes.single;
      return 'PieceVisited(${p.file}, ${p.rank}, PieceType.$name)';
    case 'pieceDropped':
      final String name = p.pieceTypes.single;
      return 'PieceDropped(${p.file}, ${p.rank}, PieceType.$name)';
    case 'handEmpty':
      return 'HandEmpty()';
    case 'kingIgyoku':
      return 'KingIgyoku()';
    default:
      throw ArgumentError('unsupported placement kind: ${p.kind}');
  }
}

String _dartString(String s) {
  final String escaped =
      s.replaceAll(r'\', r'\\').replaceAll("'", r"\'").replaceAll(r'$', r'\$');
  return "'$escaped'";
}
