// Forward codegen: data/castles.txt → lib/src/generated/castles.g.dart
//
// 使い方:
//   cd <repo>
//   dart run tool/generate_castles.dart
//
// data/castles.txt は人手編集の source-of-truth。本スクリプトは ASCII を
// パースし、const CastleTemplate(...) リテラルで埋めた .g.dart を出力する。

import 'dart:io';

import 'template_parser.dart';

void main() {
  final String input = File('data/castles.txt').readAsStringSync();
  final List<ParsedTemplate> templates = parseTemplateFile(input);
  final String output = generateCastleDart(templates);
  File('lib/src/generated/castles.g.dart').writeAsStringSync(output);
  stdout.writeln(
    'Wrote ${templates.length} castles to lib/src/generated/castles.g.dart',
  );
}

/// テンプレ列 → castles.g.dart 文字列。
String generateCastleDart(List<ParsedTemplate> templates) {
  final StringBuffer buf = StringBuffer();
  buf.writeln('// GENERATED by tool/generate_castles.dart. DO NOT EDIT.');
  buf.writeln('// Source: data/castles.txt');
  buf.writeln('//');
  buf.writeln('// To regenerate: dart run tool/generate_castles.dart');
  buf.writeln();
  buf.writeln("import '../castle.dart';");
  buf.writeln("import '../color.dart';");
  buf.writeln("import '../piece.dart';");
  buf.writeln();
  buf.writeln('const List<CastleTemplate> castles = <CastleTemplate>[');
  for (final ParsedTemplate t in templates) {
    buf.writeln('  CastleTemplate(');
    buf.writeln('    name: ${_dartString(t.name)},');
    if (t.parent != null) {
      buf.writeln('    parent: ${_dartString(t.parent!)},');
    }
    if (t.aliases.isNotEmpty) {
      buf.writeln(
        '    aliases: <String>[${t.aliases.map(_dartString).join(', ')}],',
      );
    }
    if (t.plyEq != null) {
      buf.writeln('    plyEq: ${t.plyEq},');
    }
    if (t.plyMax != null) {
      buf.writeln('    plyMax: ${t.plyMax},');
    }
    if (t.evaluateAtGameEnd) {
      buf.writeln('    evaluateAtGameEnd: true,');
    }
    if (t.placements.isEmpty) {
      buf.writeln('    placements: <CastleRequirement>[],');
    } else {
      buf.writeln('    placements: <CastleRequirement>[');
      for (final PlacementCell p in t.placements) {
        buf.writeln('      ${_formatPlacement(p)},');
      }
      buf.writeln('    ],');
    }
    buf.writeln('  ),');
  }
  buf.writeln('];');
  return buf.toString();
}

String _formatPlacement(PlacementCell p) {
  switch (p.kind) {
    case 'exact':
      final String enumName = p.pieceTypes.single;
      return 'PiecePlacement(${p.file}, ${p.rank}, PieceType.$enumName)';
    case 'opponent':
      final String enumName = p.pieceTypes.single;
      return 'PiecePlacement(${p.file}, ${p.rank}, '
          'PieceType.$enumName, color: Color.white)';
    case 'anyOf':
      final String opts =
          p.pieceTypes.map((String n) => 'PieceType.$n').join(', ');
      return 'AnyOfPieces(${p.file}, ${p.rank}, <PieceType>[$opts])';
    case 'empty':
      return 'EmptySquare(${p.file}, ${p.rank})';
    case 'anyPiece':
      if (p.anySide) {
        return 'AnyPiece(${p.file}, ${p.rank}, anySide: true)';
      }
      return 'AnyPiece(${p.file}, ${p.rank})';
    case 'anyPlacement':
      final String coords = p.squares
          .map((({int file, int rank}) s) => '(file: ${s.file}, rank: ${s.rank})')
          .join(', ');
      final String color = p.opponent ? ', color: Color.white' : '';
      return 'AnyPlacement(PieceType.${p.pieceTypes.single}, '
          '<({int file, int rank})>[$coords]$color)';
    case 'notOf':
      final String opts =
          p.pieceTypes.map((String n) => 'PieceType.$n').join(', ');
      final String color = p.opponent ? ', color: Color.white' : '';
      return 'NotOfPieces(${p.file}, ${p.rank}, <PieceType>[$opts]$color)';
    case 'pieceAnywhere':
      return 'PieceAnywhere(PieceType.${p.pieceTypes.single})';
    case 'handPiece':
      final String name = p.pieceTypes.single;
      if (p.opponent) {
        return 'HandPiece(PieceType.$name, ${p.minCount}, Color.white)';
      }
      if (p.minCount == 1) {
        return 'HandPiece(PieceType.$name)';
      }
      return 'HandPiece(PieceType.$name, ${p.minCount})';
    case 'pieceUnmoved':
      return 'PieceUnmoved(${p.file}, ${p.rank})';
    case 'pieceVisited':
      final String name = p.pieceTypes.single;
      return 'PieceVisited(${p.file}, ${p.rank}, PieceType.$name)';
    case 'pieceDropped':
      final String name = p.pieceTypes.single;
      return 'PieceDropped(${p.file}, ${p.rank}, PieceType.$name)';
    case 'handEmpty':
      return 'HandEmpty()';
    case 'kingIgyoku':
      return 'KingIgyoku()';
    default:
      throw ArgumentError('unsupported placement kind: ${p.kind}');
  }
}

String _dartString(String s) {
  // Dart literal: use single quotes; escape backslash and single quote and $.
  final String escaped =
      s.replaceAll(r'\', r'\\').replaceAll("'", r"\'").replaceAll(r'$', r'\$');
  return "'$escaped'";
}
