// Forward codegen: data/strategies.txt → lib/src/generated/strategies.g.dart
//
// 使い方:
//   cd <repo>
//   dart run tool/generate_strategies.dart

import 'dart:io';

import 'template_parser.dart';

void main() {
  final String input = File('data/strategies.txt').readAsStringSync();
  final List<ParsedTemplate> templates = parseTemplateFile(input);
  final String output = generateStrategyDart(templates);
  File('lib/src/generated/strategies.g.dart').writeAsStringSync(output);
  stdout.writeln(
    'Wrote ${templates.length} strategies to '
    'lib/src/generated/strategies.g.dart',
  );
}

/// テンプレ列 → strategies.g.dart 文字列。
String generateStrategyDart(List<ParsedTemplate> templates) {
  final StringBuffer buf = StringBuffer();
  buf.writeln('// GENERATED by tool/generate_strategies.dart. DO NOT EDIT.');
  buf.writeln('// Source: data/strategies.txt');
  buf.writeln('//');
  buf.writeln('// To regenerate: dart run tool/generate_strategies.dart');
  buf.writeln();
  buf.writeln("import '../castle.dart';");
  buf.writeln("import '../piece.dart';");
  buf.writeln("import '../strategy.dart';");
  buf.writeln();
  buf.writeln('const List<StrategyTemplate> strategies = <StrategyTemplate>[');
  for (final ParsedTemplate t in templates) {
    buf.writeln('  StrategyTemplate(');
    buf.writeln('    name: ${_dartString(t.name)},');
    if (t.parent != null) {
      buf.writeln('    parent: ${_dartString(t.parent!)},');
    }
    if (t.aliases.isNotEmpty) {
      buf.writeln(
        '    aliases: <String>[${t.aliases.map(_dartString).join(', ')}],',
      );
    }
    if (t.side != null && t.side != 'either') {
      buf.writeln('    side: StrategySide.${t.side},');
    }
    if (t.plyEq != null) {
      buf.writeln('    plyEq: ${t.plyEq},');
    }
    if (t.plyMax != null) {
      buf.writeln('    plyMax: ${t.plyMax},');
    }
    if (t.evaluateAtGameEnd) {
      buf.writeln('    evaluateAtGameEnd: true,');
    }
    if (t.placements.isEmpty) {
      buf.writeln('    placements: <CastleRequirement>[],');
    } else {
      buf.writeln('    placements: <CastleRequirement>[');
      for (final PlacementCell p in t.placements) {
        buf.writeln('      ${_formatPlacement(p)},');
      }
      buf.writeln('    ],');
    }
    buf.writeln('  ),');
  }
  buf.writeln('];');
  return buf.toString();
}

String _formatPlacement(PlacementCell p) {
  switch (p.kind) {
    case 'exact':
      final String enumName = p.pieceTypes.single;
      return 'PiecePlacement(${p.file}, ${p.rank}, PieceType.$enumName)';
    case 'anyOf':
      final String opts =
          p.pieceTypes.map((String n) => 'PieceType.$n').join(', ');
      return 'AnyOfPieces(${p.file}, ${p.rank}, <PieceType>[$opts])';
    case 'empty':
      return 'EmptySquare(${p.file}, ${p.rank})';
    case 'anyPiece':
      return 'AnyPiece(${p.file}, ${p.rank})';
    case 'notOf':
      final String opts =
          p.pieceTypes.map((String n) => 'PieceType.$n').join(', ');
      return 'NotOfPieces(${p.file}, ${p.rank}, <PieceType>[$opts])';
    case 'pieceAnywhere':
      return 'PieceAnywhere(PieceType.${p.pieceTypes.single})';
    case 'handPiece':
      final String name = p.pieceTypes.single;
      if (p.minCount == 1) {
        return 'HandPiece(PieceType.$name)';
      }
      return 'HandPiece(PieceType.$name, ${p.minCount})';
    case 'pieceUnmoved':
      return 'PieceUnmoved(${p.file}, ${p.rank})';
    case 'pieceVisited':
      final String name = p.pieceTypes.single;
      return 'PieceVisited(${p.file}, ${p.rank}, PieceType.$name)';
    case 'kingIgyoku':
      return 'KingIgyoku()';
    default:
      throw ArgumentError('unsupported placement kind: ${p.kind}');
  }
}

String _dartString(String s) {
  final String escaped =
      s.replaceAll(r'\', r'\\').replaceAll("'", r"\'").replaceAll(r'$', r'\$');
  return "'$escaped'";
}
